   const oracleAnswers = [
      "Yes, absolutely.",
      "No, not at all.",
      "It is certain.",
      "It is unclear; ask again.",
      "The outcome looks promising.",
      "Do not count on it.",
      "Perhaps in time.",
      "You already know the answer.",
      "The stars say yes.",
      "The stars say no.",
      "Doubtful, but not impossible.",
      "A change is coming soon.",
      "It will be revealed in time.",
      "Patience will bring clarity.",
      "Focus on what matters most.",
      "Signs point to yes.",
      "Signs point to no.",
      "Now is not the right time.",
      "Take a chance.",
      "Follow your intuition.",
      "Beware of false promises.",
      "The answer lies within.",
      "Trust the process.",
      "It is destined.",
      "You must make the first move.",
      "Unlikely, but miracles happen.",
      "Your efforts will pay off.",
      "It may not go as planned.",
      "Seek advice from others.",
      "Keep an open mind.",
      "It is not yours to know.",
      "Let go of your expectations.",
      "The odds are in your favor.",
      "A new opportunity awaits.",
      "Focus on your priorities.",
      "You are on the right path.",
      "You will need to wait longer.",
      "Look for a sign.",
      "Trust in your instincts.",
      "A mystery will soon be solved.",
      "Prepare for the unexpected.",
      "Yes, but with conditions.",
      "No, but it opens another door.",
      "You must take the lead.",
      "The future is uncertain.",
      "Be cautious with your choices.",
      "It is up to you.",
      "The timing is perfect.",
      "Now is the time to act.",
      "Wait and see.",
      "The outcome depends on your actions.",
      "It is too soon to tell.",
      "An unexpected event will change things.",
      "Yes, but not as you expect.",
      "No, but another path is better.",
      "The answer lies in the past.",
      "Reconsider your question.",
      "You must trust the journey.",
      "The answer is closer than you think.",
      "Take it one step at a time.",
      "The answer will come in a dream.",
      "Ask yourself: what do you truly want?",
      "The result will surprise you.",
      "The path is clear.",
      "You will find your way.",
      "Follow your heart.",
      "Courage will bring success.",
      "Do not fear change.",
      "It is written in the stars.",
      "You are not ready to know.",
      "The answer is yes, but later.",
      "The answer is no, but another way exists.",
      "Take time to reflect.",
      "A new perspective is needed.",
      "You are stronger than you think.",
      "The situation will improve.",
      "Focus on your goals.",
      "Yes, but only if you believe.",
      "No, but don't give up hope.",
      "Seek guidance from within.",
      "The answer will come when you least expect it.",
      "Prepare for challenges ahead.",
      "Look deeper for the truth.",
      "Trust in divine timing.",
      "You must let go to move forward.",
      "The answer is yes, for now.",
      "The answer is no, but it is for the best.",
      "Embrace the unknown.",
      "Your path will soon be illuminated.",
      "You have the power to change the outcome.",
      "An unexpected ally will help you.",
      "Yes, but with great effort.",
      "No, but there is a lesson to learn.",
      "Your persistence will be rewarded.",
      "You must be patient.",
      "Let your curiosity guide you.",
      "The answer is closer than it appears.",
      "Keep moving forward.",
      "The outcome is unclear.",
      "Trust in the wisdom of others.",
      "A breakthrough is coming.",
      "Stay true to yourself.",
      "Yes, but it will take time.",
      "No, but another chance will come.",
      "Your dreams hold the answer.",
      "Do not rush into decisions.",
      "Listen to your heart.",
      "The universe is on your side.",
      "All signs point to success.",
      "Do not lose hope.",
      "Your intuition is correct.",
      "The truth will be revealed.",
      "The answer is already within you.",
      "You will find the answer in silence.",
      "Look to the future.",
      "The answer is hidden in plain sight.",
      "Be patient, the answer will come.",
      "Your hard work will pay off.",
      "Be prepared for surprises.",
      "The answer is yes, but tread carefully.",
      "The answer is no, but trust the outcome.",
      "You are closer than you think.",
      "Focus on the present.",
      "The journey is as important as the destination.",
      "You will find clarity soon.",
      "Your courage will be rewarded.",
      "The answer will come from an unexpected source.",
      "Trust the wisdom of those around you.",
      "A new beginning is near.",
      "You must let go of doubt.",
      "The answer is yes, but it requires sacrifice.",
      "The answer is no, but it opens another door.",
      "A new opportunity will present itself.",
      "The truth lies within your grasp.",
      "You already have the answer.",
      "Let your intuition guide you.",
      "A great change is on the horizon.",
      "You must trust yourself.",
      "The answer is yes, but take caution.",
      "The answer is no, but all is not lost.",
      "Believe in your abilities.",
      "Your path will become clear.",
      "The answer lies in your actions.",
      "The future holds great promise.",
      "Stay hopeful.",
      "You will overcome any obstacle.",
      "Your patience will be rewarded.",
      "The answer is yes, but not now.",
      "The answer is no, but there is more to discover.",
      "The solution is within reach.",
      "Do not doubt your potential.",
      "Yes, and it will bring joy.",
      "No, but another blessing is near.",
      "Success is around the corner.",
      "The answer depends on your perspective.",
      "This is the right moment.",
      "Delays are inevitable but beneficial.",
      "Your destiny is in your hands.",
      "A wise choice will lead to yes.",
      "An impulsive choice may lead to no.",
      "Seek the advice of a friend.",
      "The answer lies in the journey.",
      "Open your heart to possibilities.",
      "Your fears are holding you back.",
      "Yes, but expect challenges.",
      "No, but it is a chance to grow.",
      "Great fortune is coming your way.",
      "Be honest with yourself.",
      "You already hold the key.",
      "Do not let negativity cloud your judgment.",
      "Your actions will determine the outcome.",
      "Yes, and it will bring unexpected rewards.",
      "No, but you are on the right path.",
      "Focus on the lesson, not the outcome.",
      "Your intuition will guide you.",
      "The universe will guide you.",
      "The stars align in your favor.",
      "A small action will lead to big results.",
      "You must be brave.",
      "The answer is hidden in your daily life.",
      "Your path is unfolding as it should.",
      "Be willing to adapt.",
      "A surprise awaits you.",
      "Yes, with perseverance.",
      "No, but it is a chance to start anew.",
      "Follow your passions.",
      "The timing is not yet right.",
      "It is a definite yes.",
      "It is a definite no.",
      "Find balance in your approach.",
      "You will succeed if you trust yourself.",
      "The outcome may exceed your expectations.",
      "The answer lies in your relationships.",
      "Reflect on your intentions.",
      "Stay grounded and the answer will come.",
      "Yes, with the help of others.",
      "No, but clarity will follow.",
      "Your happiness is within reach.",
      "Focus on self-discovery.",
      "You must take a leap of faith.",
      "Your resilience will lead to success.",
      "Trust that you are protected.",
      "The answer is yes, with a twist.",
      "The answer is no, but a gift is coming.",
      "Your destiny is being shaped.",
      "Yes, and it will transform your life.",
      "No, but something better awaits.",
      "Your persistence is key.",
      "The signs will reveal the answer.",
      "Find peace in the unknown.",
      "The answer will surprise even you.",
      "Seek the wisdom of your elders.",
      "The journey begins with a single step.",
      "Your kindness will open new doors.",
      "The answer is yes, with caution.",
      "The answer is no, but opportunity calls.",
      "Your past will guide your future.",
      "Stay the course; the answer will come.",
      "You are destined for greatness.",
      "Your path will bring unexpected joys.",
      "You must first overcome fear.",
      "A challenge will bring clarity.",
      "Your answer lies in helping others.",
      "Yes, but only with honesty.",
      "No, but remain optimistic.",
      "A secret will be revealed.",
      "The answer lies in your dreams.",
      "Take the next step with confidence.",
      "A new adventure begins soon.",
      "Your truth will set you free.",
      "Yes, but stay humble.",
      "No, but your wisdom will grow.",
      "Expect the unexpected.",
      "Only time will tell.",
      "The answer is unclear for now.",
      "Focus on the bigger picture.",
      "Success is within your reach.",
      "The truth may surprise you.",
      "You already know what to do.",
      "The timing isn't right yet.",
      "It is better to wait.",
      "A new opportunity is on its way.",
      "The answer will be revealed soon.",
      "Do not let doubt cloud your mind.",
      "Unexpected events will unfold.",
      "You will achieve your goals.",
      "Prepare for the unexpected.",
      "You must believe in yourself.",
      "The answer is yes, but take action.",
      "The answer is no, but have faith.",
      "A change in perspective is needed.",
      "Your efforts will bear fruit.",
      "Seek wisdom from others.",
      "Look within for guidance.",
      "Now is the time to trust your instincts.",
      "The signs are all around you.",
      "A great opportunity awaits you.",
      "The answer lies in your past actions.",
      "Patience is the key.",
      "Trust in the natural flow.",
      "Yes, but not without challenges.",
      "No, but brighter days are ahead.",
      "You are on the right track.",
      "Embrace the process.",
      "A twist of fate is coming.",
      "Your question will soon be answered.",
      "The answer is unclear; wait for a sign.",
      "Have faith in the unknown.",
      "Take a step back to see clearly.",
      "Your future is bright.",
      "The stars are aligning in your favor.",
      "Let go of unnecessary worries.",
      "You have the strength to overcome this.",
      "A resolution is near.",
      "Do not give up now.",
      "Yes, but only if you take the first step.",
      "No, but better opportunities await.",
      "A new chapter begins soon.",
      "Be open to new possibilities.",
      "You will find what you are looking for.",
      "Clarity will come with time.",
      "The answer is not what you expect.",
      "Let go of your fears.",
      "Focus on the present moment.",
      "Good things come to those who wait.",
      "Be patient; the answer will arrive.",
      "Your hard work is about to pay off.",
      "You are closer to success than you think.",
      "The journey is just beginning.",
      "Seek help from unexpected places.",
      "The truth will come to light soon.",
      "A surprising turn of events is near.",
      "Take things one day at a time.",
      "The universe is guiding you.",
      "Yes, but stay cautious.",
      "No, but an alternative is better.",
      "Your destiny is unfolding.",
      "Open your heart to new opportunities.",
      "A leap of faith is required.",
      "The answer lies in simplicity.",
      "Clear your mind for clarity.",
      "The odds are in your favor.",
      "You are capable of great things.",
      "Do not let fear hold you back.",
      "Something wonderful is about to happen.",
      "The answer may surprise you.",
      "You must act with courage.",
      "Follow your instincts, they are right.",
      "The answer will be found in time.",
      "Focus on the outcome you desire.",
      "The truth is within your grasp.",
      "It is not yet time to act.",
      "Your persistence will be rewarded.",
      "A fresh perspective will help.",
      "Let go of unnecessary distractions.",
      "A chance encounter will guide you.",
      "The result depends on your actions.",
      "You are closer than you realize.",
      "The journey will teach you much.",
      "Your resilience will lead to success.",
      "Seek balance in all you do.",
      "Unexpected support is on its way.",
      "A decision must be made soon.",
      "Your question holds great potential.",
      "A wise choice leads to success.",
      "Be mindful of your surroundings.",
      "Happiness is within your reach.",
      "Trust the process; it’s unfolding.",
      "Prepare for a moment of clarity.",
      "A breakthrough is just around the corner.",
      "The answer will come from someone close.",
      "Focus on growth and progress.",
      "The solution may surprise you.",
      "Your efforts are not in vain.",
      "Remain steadfast; success is near.",
      "The answer is yes, but tread lightly.",
      "No, but a better option is near.",
      "Your creativity will guide you.",
      "Embrace new opportunities without fear.",
      "Trust that all will be well.",
      "Yes, but with unexpected challenges ahead.",
      "No, but there is wisdom to gain.",
      "The answer lies in your hands.",
   "A calm mind will reveal the way.",
   "Do not be afraid to start over.",
   "Yes, but only if you stay focused.",
   "No, but new doors will open soon.",
   "The path forward will surprise you.",
   "Your potential is limitless.",
   "A wise decision will bring success.",
   "It is time to take action.",
   "You must remain adaptable.",
   "Your patience will soon pay off.",
   "An important lesson is at hand.",
   "Focus on what truly matters.",
   "Good fortune is on its way.",
   "Your question has many answers.",
   "The answer is found in collaboration.",
   "A small step will lead to big changes.",
   "The future holds great promise.",
   "The answer is yes, but stay vigilant.",
   "The answer is no, but it's a blessing.",
   "A helping hand will make a difference.",
   "Stay open to unexpected ideas.",
   "A turning point is approaching.",
   "Success requires a leap of faith.",
   "The answer is yes, if you believe.",
   "The answer is no, but all is not lost.",
   "Clarity comes from within.",
   "A bold move will bring rewards.",
   "You must embrace the present moment.",
   "Your instincts are leading you well.",
   "Be patient with the process.",
   "The answer lies in simplicity.",
   "Unexpected events will change the outcome.",
   "Your strength will guide you through.",
   "It’s time to let go of the past.",
   "Your intuition holds the key.",
   "Seek joy in the journey.",
   "The answer is yes, but not without effort.",
   "The answer is no, but hope remains.",
   "A new path is about to emerge.",
   "Let your courage shine through.",
   "The signs are pointing to success.",
   "Your question holds great potential.",
   "An unexpected ally will appear.",
   "Yes, but timing is everything.",
   "No, but better things await.",
   "A creative approach is needed.",
   "Trust in your inner wisdom.",
   "The answer lies in seeking balance.",
   "Take a risk; it will pay off.",
   "Your hard work will soon bear fruit.",
   "It’s not the right time to decide.",
   "Keep faith in the unknown.",
   "A positive shift is coming.",
   "The solution is closer than you think.",
   "The answer is yes, but tread carefully.",
   "No, but new opportunities are near.",
   "Your persistence will be your strength.",
   "Stay true to your vision.",
   "A decision today will shape tomorrow.",
   "Look beyond the surface for clarity.",
   "Trust in the flow of events.",
   "The answer is yes, if you act boldly.",
   "The answer is no, but it leads to growth.",
   "A powerful transformation is ahead.",
   "Your efforts are about to be recognized.",
   "Seek harmony in your choices.",
   "The answer is yes, but take it slow.",
   "The answer is no, but keep exploring.",
   "The truth is unfolding around you.",
   "Your adaptability will serve you well.",
   "The path you seek is within reach.",
   "Yes, but not in the way you expect.",
   "No, but a better outcome awaits.",
   "A spark of inspiration will guide you.",
   "Your question holds great promise.",
   "Remain focused on your goals.",
   "The answer is in your daily actions.",
   "You will find the strength you need.",
   "A pivotal moment is approaching.",
   "It’s time to embrace change.",
   "Your curiosity will lead to success.",
   "Yes, but be ready for challenges.",
   "No, but valuable lessons lie ahead.",
   "Trust the journey; it’s leading you well.",
   "A breakthrough is on the horizon.",
   "Keep an open heart and mind.",
   "Your determination will bring success.",
   "The answer lies in unexpected places.",
   "Focus on progress, not perfection.",
   "Your dreams hold important clues.",
   "Yes, but only if you stay consistent.",
   "No, but the experience will shape you.",
   "A surprising opportunity will come soon.",
   "Believe in the power of your actions.",
   "A moment of clarity is near.",
   "The answer is yes, but requires effort.",
   "The answer is no, but another path is better.",
   "Your question holds hidden potential.",
   "A supportive presence will assist you.",
   "The future is brighter than you think.",
   "Stay grounded and move forward.",
   "The answer lies within you, trust your intuition and follow your inner guidance.",
   "Patience is your ally. Take time to reflect, for the path will become clearer with each step.",
   "What you seek is already on its way, but the timing must be right. Trust the process.",
   "Seek balance, for harmony will guide you to the right solution in all matters.",
   "Do not fear change, for it is a natural part of growth. Embrace the opportunities it brings.",
   "The key to success lies in persistence. Keep moving forward, even when the path seems unclear.",
   "The world is full of possibilities. Keep an open mind, and the right answer will reveal itself in due time.",
   "In times of uncertainty, look within for clarity. Trust your instincts, and they will guide you.",
   "Your future is shaped by your actions today. Make choices with intention, and the path will unfold before you.",
   "Look beyond the surface. True answers often lie deeper, and understanding comes with patience.",
   "You are more connected than you realize. Trust the interconnectedness of all things, and the right path will emerge.",
   "The journey is just as important as the destination. Be present in each moment, and the answers will come naturally.",
   "The right path is one of self-awareness. The more you know yourself, the more you will see the way forward.",
   "Everything will work out in the end. Trust that the universe has a plan for you, even if it’s not clear now.",
   "You are exactly where you need to be. Sometimes, the answers come when we least expect them.",
   "You’ve done the best you can, and that’s enough. Trust that things will align as they should.",
   "Don’t worry, everything happens for a reason. The universe has a way of making things right in the end.",
   "You are on the right track, even if it doesn’t feel that way. The path will reveal itself in time.",
   "Things may seem unclear now, but remember: every experience is a step towards clarity.",
   "All will be well. Trust that whatever happens next is exactly what you need.",
   "Take a deep breath. Sometimes, things work out when you stop trying to force them to.",
   "Sometimes, not knowing is part of the journey. Rest easy, the answers will reveal themselves when the time is right.",
   "You’ve already made great progress, even if you don’t see it yet. Keep moving forward with trust.",
   "Take comfort in knowing that you’re never truly lost; you’re just finding your way, step by step.",
   "Trust that everything is unfolding as it should. Your journey is unique, and you’re exactly where you need to be.",
   
   "Look to the left. There is something small there, it might just be the key you need. Look carefully.",
   "The answer lies in a place you’ve been before, but this time, approach it from a different angle.",
   "When you find yourself in a quiet moment, take a deep breath. It is in that stillness you will know the next step.",
   "There’s a small detail you’ve overlooked. Perhaps it’s something familiar, but now it holds more significance.",
   "When in doubt, return to simplicity. It’s not always about complexity—sometimes the simplest solution is the right one.",
   "The path forward is hidden, but it lies in your recent experiences. Reflect on the last choice you made, it may hold the answer.",
   "Look around. There’s something in your current environment that has been trying to get your attention. Trust what you feel about it.",
   "Trust your first instinct. The answer is simpler than you realize, but only if you stop overthinking.",
   "Take a moment to step back and observe. The answer might not be clear right away, but it will reveal itself with time.",
   "There’s a whisper in the wind—pay attention to it. It’s guiding you, though you may not recognize it yet.",
   "The key to your question is likely something that feels trivial. What seems insignificant today may become clear tomorrow.",
   "When you least expect it, you will find the answer in the most ordinary place. Keep your mind open and stay alert to the everyday moments.",
   
   "You have been on the right path all along, but there’s something small left undone. Pay attention to the next step.",
   "Something in the air feels lighter. Trust that this calmness will lead you toward the right answer.",
   "Your thoughts are being guided. Listen carefully to the quiet voice inside; it knows what’s next.",
   "Look at the people around you. They may not have all the answers, but they hold a piece of the puzzle.",
   "The solution you seek is in a conversation you’re about to have. Keep your ears open.",
   "The answer will come when you stop looking for it. Take a step back and let it find you.",
   "A gentle shift in your routine may be all it takes to reveal the truth you seek. Don’t be afraid to try something new.",
   "The sky is clearer than it seems. Trust that the clouds will part, and soon the answer will be obvious.",
   "There is strength in your silence. Take a moment and observe without the need to act.",
   "Sometimes, the hardest part is simply beginning. Take that first step, and the rest will follow.",
   "Don’t rush the process. Take each moment as it comes, and trust that everything is falling into place.",
   "Look for signs in the everyday. Sometimes the answer is hidden in the most ordinary occurrences.",
   
   "The solution is simple, but you may need to be still for a moment to see it.",
   "You have the tools you need. It’s not about finding more; it’s about using what you already have.",
   "The key to unlocking your path lies in your ability to adapt. Flexibility will guide you to success.",
   "Trust that there is no wrong decision. Each step is leading you toward the right place.",
   "Don’t be afraid to pause. Sometimes standing still is the best way to move forward.",
   "You are aligned with your purpose. Everything you need will come at the right time.",
   "Look at things from a new perspective. What once seemed unclear may now come into focus.",
   "Remember to trust the process. There’s no need to rush; you’re exactly where you need to be.",
   "The answer is already inside you. All that is needed is time to listen and reflect.",
   "Rest easy. Even when you can’t see the path ahead, trust that it is unfolding as it should.",
   "The change you seek is already in motion. Just wait and watch, and soon you will see the fruits of your efforts.",
   "An unexpected shift is coming your way. Embrace it, for it will bring clarity.",
   
   "The stars are aligned, but they require you to take the first step. Don’t wait for the universe to push you.",
   "Trust your instincts now more than ever. Your inner voice knows the way forward.",
   "Sometimes the best answer is a quiet one. Stop searching and let it come to you.",
   "Your future is filled with promise. Every challenge you face is preparing you for something greater.",
   "There’s something you’ve been overlooking. Step back, breathe, and you’ll see it clearly now.",
   "The answer will come from within. It may not be clear at first, but trust the wisdom of your heart.",
   "You’re on the verge of discovery. Keep pushing forward just a little longer, and the answer will present itself.",
   "Let go of your fear. The universe is guiding you exactly where you need to go.",
   "You’ve been preparing for this moment your entire life. Trust that you’re ready to make the next move.",
   "Pay attention to your dreams. They are guiding you toward the answer you seek.",
   "The world is vast, but you are connected to all things. Trust that the answer is within reach.",
   "Your journey is unique. Trust that every experience is teaching you what you need to know.",
   
   "The truth you seek is closer than you think. Look for it in unexpected places.",
   "You have all the time you need. Don’t rush, and the answer will reveal itself when it’s meant to.",
   "Everything is unfolding perfectly. The pieces will fit together when the time is right.",
   "There is no need to worry. Things will resolve themselves in due time, just trust the journey.",
   "Look for patterns. The universe speaks to you in subtle ways, guiding you to the answers you seek.",
   "Trust that your instincts are leading you in the right direction. Don’t second-guess yourself.",
   "You are supported. Even when it feels like you’re alone, the universe is working in your favor.",
   "Take a step back and breathe. You are not lost. You are simply on the verge of a new discovery.",
   "Your heart knows the way. Follow it, and the answers will become clear.",
   "Sometimes, the most powerful thing you can do is surrender. Let go, and trust that everything will align.",
   "Stay open to the unexpected. The solution may come from a direction you least expect.",
   "What you seek is already in motion. Simply trust that it will manifest at the right moment.",
   
   "The universe has a plan for you, but it requires you to take the next step. Don’t hesitate.",
   "The answer is always simpler than it appears. Step back and look at the situation from a fresh perspective.",
   "You are being led toward a breakthrough. Trust that the challenges you face are preparing you for something greater.",
   "There is a lesson in everything. Pay attention to the small moments, for they hold the key.",
   "Trust that everything you’ve experienced has been preparing you for the path ahead. Keep moving forward.",
   "Sometimes the best answers come when you stop searching. Let the universe reveal them in its own time.",
   "Pay attention to the small details. The answer to your question is closer than you realize.",
   "Look around you. The world is full of clues. Trust that the answers will appear when you are ready to see them.",
   "You are exactly where you need to be. Don’t doubt yourself. Everything is unfolding as it should.",
   "The truth is unfolding, and it will become clearer when you least expect it. Trust the process.",
   "Take a moment to be still. The answers are coming, and you are closer to discovering them than you think.",
   "Sometimes, the right answer requires patience. Wait, and trust that it will come to you when the time is right.",
   
   "Your path is leading you in the right direction. Trust the steps that are being laid before you.",
   "Look for guidance from those around you. They may offer a perspective that shifts your view.",
   "Trust that what you need will come to you in time. There is no need to rush.",
   "The answer lies just beyond the horizon. Keep moving forward, and you’ll find it.",
   "The key is within your grasp. Trust that when you are ready, it will be revealed.",
   "Take heart. Every experience is preparing you for the answer that will come soon.",
   "Stay patient. The universe is aligning everything you need. Trust that it will all come together.",
   "Look within. The solution is closer than you realize.",
   "You’ve been on this path for a reason. Trust that each step you’ve taken has brought you closer to the answer.",
   "The answer will come when you stop trying to force it. Relax and let it come naturally.",
   "Your intuition knows the way. Trust it, and you’ll find the answer you seek.",
   "It is time to trust in yourself. You have everything you need to move forward.",
   
   "The winds are shifting. Trust that they are guiding you in the right direction.",
   "When you feel uncertain, return to what feels familiar. Sometimes, home is the place where the answer lies.",
   "Trust that you have all the tools you need. They will become clear to you when the time is right.",
   "The answer is in front of you, but it may take time to recognize it. Keep looking, and it will appear.",
   "Remember, the solution isn’t always immediate. Give yourself space to see it when it reveals itself.",
   "You are being guided in ways you cannot see. Trust that each moment brings you closer to the truth.",
   "Be patient with yourself. The answer will come at the right time, and you’ll know it when you feel it.",
   "You are on the right path. Every step you take is leading you toward the answer you seek.",
   "The solution may not be what you expect, but it will be exactly what you need.",
   "Let go of expectations. The answer will come when you stop trying to control it.",
   "Your next step is clearer than you think. Trust that it will be revealed to you when the time is right.",
   "Everything is falling into place. Trust the process and be open to the answers that come your way.",
   "You have the power to shape your destiny. Step forward with confidence and clarity.",
   "The strength you seek is already within you. Trust yourself, and you’ll see it unfold.",
   "Everything you need is already inside you. Tap into your power and trust your decisions.",
   "Your will is strong, and your actions will pave the way. Trust that every step leads to success.",
   "You are the architect of your future. Build with courage and confidence.",
   "Your inner wisdom knows the way. Follow it, and you’ll see your dreams come true.",
   "Believe in yourself, and the universe will align with your efforts.",
   "The challenges you face are the very things that will make you stronger. Embrace them.",
   "Don’t doubt your abilities. You have already overcome so much, and there’s more to come.",
   "Trust yourself, for you have what it takes to turn your vision into reality.",
   "The universe believes in you, and now it's your turn to believe in yourself.",
   "You are capable of great things. Stay persistent, and you will see your efforts rewarded.",
   "Your success is inevitable. Trust the process and remain consistent in your actions.",
   "You have everything you need to succeed. It’s time to unleash your potential.",
   "Strength comes from within. Draw from your inner resources, and success will follow.",
   "Keep moving forward; the universe is aligning to bring you the opportunities you seek.",
   "Trust the voice within you, for it knows the way better than anyone else.",
   "The world is waiting for you to shine. Step into your greatness without hesitation.",
   "You are already equipped to face what’s ahead. Trust that the path is already open.",
   "The universe is supporting your every move. Trust and act with confidence.",
   "The power to create your future lies in your hands. Don’t hold back.",
   "When you trust yourself, the world will align to support your vision.",
   "The energy you put into the world returns to you. Stay positive and keep moving forward.",
   "What you desire is already on its way. Trust that your efforts are being recognized.",
   "You are more resilient than you realize. Embrace every challenge as an opportunity to grow.",
   "There is no obstacle you cannot overcome. Your inner strength will carry you through.",
   "Success is your birthright. Believe in it, and it will be yours.",
   "Every decision you make is a step toward your destined future. Trust the process.",
   "Your dreams are not out of reach. With persistence and belief, they are already yours.",
   "You are destined for greatness. Your actions today will shape tomorrow’s success.",
   "You have all the tools you need to make your vision a reality. Start now.",
   "You are the creator of your own destiny. Your actions will shape your world.",
   "The universe is preparing the perfect moment for you. Trust that it is coming soon.",
   "Your success is written in the stars. All you have to do is take the first step.",
   "Believe in your abilities, and the universe will open doors you never imagined.",
   "Trust your instincts, for they have guided you this far. They will continue to lead you.",
   "You are capable of turning your dreams into reality. Take the next step with confidence.",
   "Everything you need to succeed is already within you. Let it guide you forward.",
   "The future is yours to shape. Trust that your efforts will lead to the success you desire.",
   "Embrace your power. The world is waiting for you to step into your purpose.",
   "With every challenge, you grow stronger. Keep pushing forward, and success will follow.",
   "You are capable of overcoming anything that stands in your way. Keep going.",
   "You are more than capable of achieving everything you desire. Trust the process.",
   "Your inner wisdom holds the key to your success. Let it guide your actions.",
   "The path to success is already unfolding before you. Trust in your journey.",
   "The time to act is now. Take the first step toward your future today.",
   "There is no limit to what you can achieve. Believe in yourself and move forward.",
   "You hold the key to your own success. Unlock it with courage and confidence.",
   "You are already equipped to handle what lies ahead. Trust in yourself.",
   "The universe is aligning to bring your dreams to life. Trust and take action.",
   "You are on the right path. Keep moving forward with confidence and clarity.",
   "Your dreams are achievable. Trust yourself and take the next step.",
   "With every challenge, you gain strength and wisdom. Keep going, for success is near.",
   "Trust your instincts. They will lead you to where you need to be.",
   "Your potential is limitless. Don’t hold back—go after what you want.",
   "You are capable of great things. Trust that the universe supports you on this journey.",
   "Success is within your reach. Take the leap of faith and trust that you will land on your feet.",
   "You are in control of your destiny. Trust that every step you take is leading you toward success.",
   "The future is bright. Trust in yourself, and the universe will open the way.",
   "The strength to overcome any challenge is already within you. Tap into it and move forward.",
   "The world is ready for your greatness. Step forward and let it unfold.",
   "Your potential is unlimited. Take action, and the universe will support your efforts.",
   "The time to act is now. Trust yourself and move forward with confidence.",
   "Every step you take is a step closer to your goals. Keep going.",
   "Your actions today will shape the world of tomorrow. Trust that the universe has your back.",
   "You are on the right track. Keep believing in yourself and your abilities.",
   "Trust that the universe is guiding you toward success, one step at a time.",
   "You have everything you need to succeed. Trust your instincts and take the next step.",
   "Greatness is within your reach. Believe in yourself, and the universe will support you.",
   "You are more than capable of achieving your goals. Trust in your abilities.",
   "The future is yours to create. Trust in your power and take the next step.",
   "You are stronger than you know. Trust in your abilities and take action now.",
   "The universe supports your dreams. Trust that success is on the horizon.",
   "You are ready for the challenges ahead. Trust yourself and move forward with confidence.",
   "Your dreams are within reach. Trust the process, and success will follow.",
   "Keep believing in yourself. The universe is aligning to bring you everything you desire.",
   "Your inner strength will guide you to success. Trust in your abilities.",
   "The world is full of opportunities. Keep your mind open, and you will see them.",
   "Success is coming your way. Trust yourself, and it will manifest.",
   "You are capable of achieving great things. Trust in yourself and take the next step.",
   "Your potential knows no bounds. Believe in yourself, and the universe will make it happen.",
   "Take action now, for your future self will thank you for it.",
   "The time to make your dreams a reality is now. Trust that everything you need is already within you.",
   "Your destiny is yours to create. Believe in it, and it will unfold before you.",
   "The world is ready for you to shine. Step into your power and let your light illuminate the path ahead.",
   "You have everything you need to succeed. Take action, and the universe will align to support you.",
   "You are capable of overcoming any obstacle. Trust in your strength and keep moving forward.",
   "The path ahead may be uncertain, but trust that you are exactly where you need to be.",
   "Everything is unfolding as it should. Trust the process, and everything will fall into place.",
   "The answer you seek is hidden in plain sight, waiting for you to recognize it.",
   "When the moon fades, the truth will be revealed. Patience is your ally.",
   "In the quiet moments, listen closely. The answer will come in a whisper.",
   "Not all paths are straight. Sometimes, you must walk in circles to see the way forward.",
   "Look not just at what is in front of you, but at what lies beyond the horizon.",
   "The answer will reveal itself when you least expect it. Stay open to the signs.",
   "There is wisdom in the unknown. Let go of certainty and embrace the mystery.",
   "The stars have aligned, but only when you gaze with open eyes will you see their guidance.",
   "A shift in perspective will allow the answers to reveal themselves.",
   "Not all things are meant to be understood immediately. Trust that the truth will unfold in time.",
   "When the fog lifts, the path will be clear.",
   "The truth hides in the silence between words. Listen closely, and you will hear.",
   "What is in the shadow will eventually be brought to the light.",
   "Sometimes, the answer lies within the question itself. Rethink what you ask.",
   "The journey itself is the key, not the destination.",
   "The answer is written in the patterns you see. Pay attention to the signs around you.",
   "A puzzle may seem unsolvable, but only because the pieces are scattered. Gather them.",
   "You are standing at the crossroads, but the way forward is not always obvious.",
   "What you seek is not out there, but inside you. Look inward for clarity.",
   "What you know may not be what you need to know. There is more beneath the surface.",
   "Sometimes, the simplest answers are the hardest to see.",
   "What you feel in your heart is the truth, but you must listen carefully.",
   "There are layers to every situation, each one revealing a deeper truth. Peel them back.",
   "The question itself holds the clue to the answer. Seek understanding in your inquiry.",
   "It’s not the path you take, but the journey within that will guide you.",
   "The answer is close, but it may be disguised. Search with an open mind.",
   "There is no need to rush. The answer will come at the right time.",
   "What is hidden will be revealed when the time is right. Patience is key.",
   "The key to unlocking the mystery is in what you don't understand yet.",
   "The truth is often simpler than it appears, but that simplicity can be elusive.",
   "What you seek will reveal itself in unexpected ways. Be open to the signs.",
   "The answer lies in the silence between the questions.",
   "Trust in the journey, for it will lead you to the answers you seek.",
   "What is unseen is as important as what is seen. Open your mind to all possibilities.",
   "A riddle is waiting to be solved. Pay attention to the details that seem out of place.",
   "The pieces are scattered, but with patience, you will see the full picture.",
   "Sometimes, the answer isn’t in the question at all. It’s in the space between.",
   "Listen closely to the whispers of the world around you. They speak the truth.",
   "The path to your answer is not always direct. Sometimes, detours lead to the right way.",
   "The truth is not linear. It’s a spiral that leads you to where you need to be.",
   "The answer has already presented itself. It is up to you to see it.",
   "What you seek is closer than you think. But first, you must change how you see it.",
   "A subtle shift in perspective will bring the clarity you desire.",
   "The truth lies in the cracks of the world. Seek the hidden places.",
   "Not everything that appears is as it seems. Look beyond the surface.",
   "The answer is not what you expect. Be prepared to find something entirely new.",
   "Everything is connected. You will find the answer in the unlikeliest of places.",
   "The truth is like a river, flowing slowly, but always moving forward. Follow its course.",
   "The signs are all around you. It is up to you to notice them.",
   "A mystery is waiting to be solved, but only you hold the key to unlocking it.",
   "Not all answers come in words. Sometimes, they come in feelings, colors, or sensations.",
   "The answer may be in the moment you are ignoring. Pay attention.",
   "Everything has its own rhythm. Trust in the flow of the universe to guide you.",
   "Sometimes, the right answer comes when you stop trying to force it.",
   "The answer you seek is hidden in the questions you have yet to ask.",
   "Look closely at the small details. They may be the answer you’ve been searching for.",
   "The truth is found not in what you are looking for, but in what you have overlooked.",
   "What you think you know may be the exact thing blocking your path to the truth.",
   "Sometimes, the most cryptic clues lead to the simplest truths.",
   "In the unknown, there is clarity. Look deeper.",
   "The answer will not arrive when you expect it, but when you are ready.",
   "What you are seeking is not outside of you, but within. Look inward for the truth.",
   "The key to unlocking the mystery is in the unexpected.",
   "What you are searching for is closer than you realize. Trust your instincts.",
   "The most powerful answers are often the ones you least expect.",
   "Listen to the world around you. It speaks in ways you cannot yet understand.",
   "The answer is in the spaces between the questions. Reflect deeply.",
   "What you are seeking may be hidden in plain sight, waiting for you to recognize it.",
   "When you release control, the answers will come to you effortlessly.",
   "The truth is always present, but you must learn how to recognize it.",
   "Answers come not when you ask, but when you are ready to hear them.",
   "Sometimes, the greatest mysteries are the ones you are meant to solve on your own.",
   "Do not seek the answer; let the answer find you.",
   "The key is hidden in the patterns of the world. Pay close attention.",
   "What you seek is unfolding quietly around you. Be patient and stay alert.",
   "A new understanding is on the horizon, but only when you are ready to accept it.",
   "What you desire is closer than you think. Trust your instincts to guide you.",
   "Every answer is a part of a larger story. Trust the process of unfolding.",
   "The answer is in the quiet moments, when you stop trying to control the outcome.",
   "What you seek will not be handed to you, but revealed when you stop searching so hard.",
   "You are on the brink of discovery. Stay vigilant and open-minded.",
   "The answer is in the questions you haven’t asked yet. Reflect deeper.",
   "Look not for answers, but for the questions that lead you to them.",
   "The truth is elusive, but with persistence, you will uncover it.",
   "There is more beneath the surface than you realize. Dig deeper.",
   "The answer is hiding in the most unexpected of places. Stay open to all possibilities.",
   "What you think you know is not the whole truth. Seek beyond your current understanding.",
   "The universe whispers to you in subtle ways. Pay attention to its messages.",
   "The answer will come when you align yourself with the flow of the universe.",
   "Not all is as it seems. What you are seeking is right under your nose.",
   "A revelation is coming, but you must be patient and open to the unexpected.",
   "Sometimes, the path becomes clear when you let go of your need for certainty.",
   "The truth lies within the contradictions. Embrace the paradox.",
   "What you seek is not far away, but within your reach if you change your approach.",
   "Patience is the key. What you seek is on its way, but only when the time is right.",
   "There is an answer waiting for you, but it will be revealed only when you are ready to see it.",
   "Seek the signs, and they will lead you to the answers you seek.",
   "The answer has been within you all along. You just need to recognize it.",
   "Look not at what you want to find, but at what the universe is trying to show you.",
   "The solution is hidden in the patterns of nature. Pay attention to the natural world around you.",
   "Every answer you seek brings you closer to a greater truth. Stay open to discovery.",
   "The truth will reveal itself, but only when you are no longer looking for it.",
   "When you embrace the unknown, the answers you seek will unfold before you.",
   "The universe works in mysterious ways. Trust that it is guiding you to the truth.",
   "What you seek is not what you expect, but exactly what you need.",
   "The truth lies just beneath the surface. You need only to peel back the layers.",
   "The signs are all around you. Open your eyes, and you will see them clearly.",
   "The answers are always right in front of you. Trust that they will appear when you need them.",
   "Your path will be illuminated when you let go of control and trust in the flow of life.",
   "The mysteries are there to guide you. Do not be afraid to uncover them.",
   "When you stop seeking, the answers will come to you in their own time.",
   "There is no doubt in this answer.",
   "Everything will happen according to plan.",
   "The next step is clear and ready for you.",
   "This is the straightforward choice.",
   "Everything is already in place.",
   "The path is already set for you.",
   "You are seeing things clearly.",
   "The question has a direct answer.",
   "You have what you need to move forward.",
   "The answer is as expected.",
   "There’s no need to question this further.",
   "The way forward is obvious.",
   "You already know what to do.",
   "Your answer is clear.",
   "This is the correct interpretation.",
   "The answer is in the details.",
   "Your question is already answered in front of you.",
   "Everything is aligned with this conclusion.",
   "The next step is ready to take.",
   "The path you need to follow is already clear.",
   "The answer will present itself quickly.",
   "The truth has already revealed itself.",
   "It’s already happening as we speak.",
   "This is the obvious choice.",
   "You’re exactly where you need to be.",
   "There is no need for second-guessing.",
   "The truth is out there for you to find.",
   "This is the solution you’ve been looking for.",
   "The answer lies in simplicity.",
   "Everything aligns with this answer.",
   "The outcome is already determined.",
   "You don’t need to search any further.",
   "You already have everything you need.",
   "It is clear and obvious to anyone who looks.",
   "When it's quiet, ask yourself.",
   "The wind whispers secrets only you can hear.",
   "Stars are simply dreams waiting to be realized.",
   "Take a step without knowing the path.",
   "Seek the answer in the silence between the words.",
   "A window opened, a shadow passed.",
   "Wall, chair, food, water.",
   "The puzzle is incomplete, yet it is whole.",
   "Listen to the stillness; it has much to say.",
   "Not all who wander are lost, but some are.",
   "Follow the path that doesn’t have footprints.",
   "Seek not with your eyes but with your soul.",
   "Where there's smoke, there’s usually something burning.",
   "A bird in the hand is an illusion of control.",
   "Look up, but don’t forget to look around.",
   "Time waits for no one, yet it stretches endlessly.",
   "The answer is in the space you don’t see.",
   "One thought leads to another, like ripples on water.",
   "The key is hidden where you least expect.",
   "A flower blooms in the mind before it appears.",
   "Listen to the echoes of your thoughts.",
   "Shadows stretch farther when you turn away.",
   "The moon is bright even when no one is watching.",
   "Move forward and the path will reveal itself.",
   "Eyes closed, the world is still moving.",
   "Turn around and find what you seek.",
   "The night is darker just before the dawn.",
   "Food, water, shelter, but what does the soul need?",
   "Seek the one who is silent but listens.",
   "Not everything that glitters is gold, but it shines nonetheless.",
   "A chair is only a chair until you sit in it.",
   "Breathe deeply; the answer is in the air.",
   "The door opens when you stop knocking.",
   "Underneath the surface, there is always more.",
   "What is lost finds its way back when you stop searching.",
   "A clock doesn’t move, yet time passes.",
   "Sometimes the question is the answer.",
   "Fire burns, but it also lights the way.",
   "You are both the question and the answer.",
   "Walk through the door, and you’ll find what lies beyond.",
   "The journey begins at the end.",
   "Familiar faces change when you look closer.",
   "The answer is not a destination, but a direction.",
   "Sometimes, the less you know, the clearer the answer becomes.",
   "Behind every corner, there is another possibility.",
   "A dream is a message you send to yourself.",
   "In stillness, find movement.",
   "A mountain looms larger from below.",
   "The answer is written in the lines you draw in your mind.",
   "The compass points north, but you create your own direction.",
   "Turn the page to reveal the next chapter.",
   "The key you seek is in your hand already.",
   "In the quietest place, find the loudest answers.",
   "A puzzle may have many pieces, but one is missing.",
   "The food you seek nourishes more than the body.",
   "Walk the path and the stones will settle beneath your feet.",
   "A question remains until you answer it.",
   "The moon hides behind the clouds, but still it shines.",
   "Water flows, but it does not wait for you.",
   "The wind carries whispers only for those who listen.",
   "The stars are your guide, but you must find your way.",
   "The door is closed, but the lock is within your reach.",
   "Sometimes the most obvious answer is the hardest to accept.",
   "Water flows uphill in dreams.",
   "A bird without wings still dreams of the sky.",
   "Look to the past for the future will be the same.",
   "Restless hands hold more than they let go.",
   "The shadow knows the way even when the sun is hiding.",
   "Is the answer hidden in the question, or is it beyond?",
   "Time has no beginning, yet it moves.",
   "A step forward is not always a step ahead.",
   "The heart whispers in a language the mind doesn’t understand.",
   "A glass half-full still holds the answer.",
   "Look behind you; you may have missed something important.",
   "Not all journeys have a destination.",
   "The walls have ears, but they are silent.",
   "Food, water, air; yet the soul is hungry.",
   "A question echoes, seeking its own answer.",
   "The quietest place can be the loudest in the heart.",
   "A chair is just a place to rest, but only if you sit.",
   "A path appears only when you start walking.",
   "Step softly, for the earth listens.",
   "The wind carries answers, but you must catch them.",
   "Follow the signs, but make your own path.",
   "In the middle of chaos, find peace.",
   "You are both the storm and the calm.",
   "The light shines brightest when the darkness is deepest.",
   "Water flows not because it knows where to go, but because it moves.",
   "Every question contains its own answer.",
   "A shadow knows its form only when there is light.",
   "Look inward for the answers the world cannot give.",
   "Food nourishes the body, but the mind craves more.",
   "When all seems still, there is movement.",
   "The answers come, but you must learn to recognize them.",
   "A question without an answer is only a beginning.",
   "The more you seek, the more the question shifts.",
   "The answer is buried under layers of thought.",
   "When you stop looking for answers, they find you.",
   "The world turns while you’re focused on your feet.",
   "What is near is often the hardest to see.",
   "The key to understanding lies in the simplest things.",
   "Nothing is as it seems, but everything is as it should be.",
   "Everything that is lost will eventually be found, but not always where you expect.",
   "Listen to the pause, for in it, the truth lies.",
   "Do not look ahead, but around you for the answer."
   ];
   let oracleAnswer;
   let randomNum1 = 12;
   let randomNum2 = 12;
   let randomNum3 = 12;
   let randomNum4 = 12;
   let randomNum5 = 12;
   let randomNum6 = 12;
   let randomNum7 = 12;
   let randomNum8 = 12;
   let randomNum9 = 12;
   let randomNum10 = 12;
   let randomNum11= 12;
   let randomNum12= 12;
   let randomM;



   
   
   console.log(Math.floor(oracleAnswer))

   document.querySelector('.js-dropdown-1').addEventListener('input',()=>{
      randomNum1 = document.querySelector('.js-dropdown-1').value
      console.log(document.querySelector('.js-dropdown-1').value)
   })
   document.querySelector('.js-dropdown-2').addEventListener('input',()=>{
      randomNum2 = document.querySelector('.js-dropdown-2').value
      console.log(document.querySelector('.js-dropdown-2').value)
   })
   document.querySelector('.js-dropdown-3').addEventListener('input',()=>{
      randomNum3 = document.querySelector('.js-dropdown-3').value
      console.log(document.querySelector('.js-dropdown-3').value)
   })
   document.querySelector('.js-dropdown-4').addEventListener('input',()=>{
      randomNum4 = document.querySelector('.js-dropdown-4').value
      console.log(document.querySelector('.js-dropdown-4').value)
   })
   document.querySelector('.js-dropdown-5').addEventListener('input',()=>{
      randomNum5 = document.querySelector('.js-dropdown-5').value
      console.log(document.querySelector('.js-dropdown-5').value)
   })
   document.querySelector('.js-dropdown-6').addEventListener('input',()=>{
      randomNum6 = document.querySelector('.js-dropdown-6').value
      console.log(document.querySelector('.js-dropdown-6').value)
   })
   document.querySelector('.js-dropdown-7').addEventListener('input',()=>{
      randomNum7 = document.querySelector('.js-dropdown-7').value
      console.log(document.querySelector('.js-dropdown-7').value)
   })
   document.querySelector('.js-dropdown-8').addEventListener('input',()=>{
      randomNum8 = document.querySelector('.js-dropdown-8').value
      console.log(document.querySelector('.js-dropdown-8').value)
   })
   document.querySelector('.js-dropdown-9').addEventListener('input',()=>{
      randomNum9 = document.querySelector('.js-dropdown-9').value
      console.log(document.querySelector('.js-dropdown-9').value)
   })
   document.querySelector('.js-dropdown-10').addEventListener('input',()=>{
      randomNum10 = document.querySelector('.js-dropdown-10').value
      console.log(document.querySelector('.js-dropdown-10').value)
   })
   document.querySelector('.js-dropdown-11').addEventListener('input',()=>{
      randomNum11 = document.querySelector('.js-dropdown-11').value
      console.log(document.querySelector('.js-dropdown-11').value)
   })
   document.querySelector('.js-dropdown-12').addEventListener('input',()=>{
      randomNum12 = document.querySelector('.js-dropdown-12').value
      console.log(document.querySelector('.js-dropdown-12').value)
   })
   document.querySelector('.js-request-button').addEventListener('click', ()=> {
      randomNum1 = randomNum1*(Math.random() *76);
      randomNum2 = randomNum2*(Math.random() *76);
      randomNum3 = randomNum3*(Math.random() *76);
      randomNum4 = randomNum4*(Math.random() *76);
      randomNum5 = randomNum5*(Math.random() *76);
      randomNum6 = randomNum6*(Math.random() *76);
      randomNum7 = randomNum7*(Math.random() *76);
      randomNum8 = randomNum8*(Math.random() *76);
      randomNum9 = randomNum9*(Math.random() *76);
      randomNum10= randomNum10*(Math.random() *76);
      randomNum11= randomNum11*(Math.random() *76);
      randomNum12= randomNum12*(Math.random() *76);
      randomM =Math.floor(Math.random()*12);
      oracleAnswer =((randomNum1 + randomNum2 + randomNum3 + randomNum4 + randomNum5 + randomNum6 + randomNum7 + randomNum8 + randomNum9 + randomNum10 + randomNum11 + randomNum12)/120 * randomM);
      document.querySelector('.js-oracle-answer').innerText = oracleAnswers[Math.floor(oracleAnswer)];
      console.log(oracleAnswer)
      oracleAnswer;
      randomNum1 = document.querySelector('.js-dropdown-1').value
      randomNum2 = document.querySelector('.js-dropdown-2').value
      randomNum3 = document.querySelector('.js-dropdown-3').value
      randomNum4 = document.querySelector('.js-dropdown-4').value
      randomNum5 = document.querySelector('.js-dropdown-5').value
      randomNum6 = document.querySelector('.js-dropdown-6').value
      randomNum7 = document.querySelector('.js-dropdown-7').value
      randomNum8 = document.querySelector('.js-dropdown-8').value
      randomNum9 = document.querySelector('.js-dropdown-9').value
      randomNum10 = document.querySelector('.js-dropdown-10').value
      randomNum11 = document.querySelector('.js-dropdown-11').value
      randomNum12 = document.querySelector('.js-dropdown-12').value
   })





 
